# Generated by Django 5.1.6 on 2025-03-10 17:41

import frontoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='question')),
                ('question_pt', models.CharField(max_length=255, null=True, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_en', models.TextField(null=True, verbose_name='answer')),
                ('answer_pt', models.TextField(null=True, verbose_name='answer')),
                ('image', models.ImageField(null=True, upload_to=frontoffice.models.faq_image_upload_to, verbose_name='image')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
            ],
        ),
    ]
