# Generated by Django 5.2.9 on 2025-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer_de',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer_es',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer_fr',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer_it',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='question_de',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='question_es',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='question_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='question_it',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
    ]
