# Generated by Django 5.1.6 on 2025-03-12 01:13

import breeding.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='name')),
                ('name_pt', models.CharField(max_length=50, null=True, unique=True, verbose_name='name')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
            ],
            options={
                'verbose_name': 'animal kind',
                'verbose_name_plural': 'animals kinds',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='description')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('?', 'Unknown')], default='?', max_length=1, verbose_name='gender')),
                ('has_training', models.BooleanField(default=False, verbose_name='has training')),
                ('for_sale', models.BooleanField(default=False, verbose_name='for sale')),
                ('price_in_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(500)], verbose_name='price in euros')),
                ('discount_in_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount in euros')),
                ('sold_at', models.DateField(blank=True, null=True, verbose_name='sold at')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_children', to='breeding.animal', verbose_name='father')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_children', to='breeding.animal', verbose_name='mother')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to=settings.AUTH_USER_MODEL, verbose_name='sold to')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnimalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=breeding.models.animal_file_upload_to, verbose_name='file')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=breeding.models.animal_file_thumbnail_upload_to, verbose_name='thumbnail')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('filename', models.CharField(editable=False, max_length=255, verbose_name='filename')),
                ('content_type', models.CharField(editable=False, max_length=50, verbose_name='content type')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='breeding.animal', verbose_name='animal')),
            ],
            options={
                'verbose_name': 'animal file',
                'verbose_name_plural': 'animal files',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_pt', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('cover', models.ImageField(upload_to=breeding.models.breed_cover_upload_to, verbose_name='cover')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='description')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', related_query_name='breed', to='breeding.animalkind', verbose_name='kind')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='breeding.breed', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'breed',
                'verbose_name_plural': 'breeds',
                'ordering': ['order'],
                'unique_together': {('kind', 'name')},
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', related_query_name='animal', to='breeding.breed', verbose_name='breed'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='description')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('breeds', models.ManyToManyField(related_name='certifications', related_query_name='certification', to='breeding.breed', verbose_name='breeds')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='breeding.certification', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnimalCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_certifications', related_query_name='animal_certification', to='breeding.animal', verbose_name='animal')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_certifications', related_query_name='animal_certification', to='breeding.certification', verbose_name='certification')),
            ],
            options={
                'verbose_name': 'animal certification',
                'verbose_name_plural': 'animal certifications',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='certifications',
            field=models.ManyToManyField(related_name='animals', related_query_name='animal', through='breeding.AnimalCertification', to='breeding.certification', verbose_name='certifications'),
        ),
    ]
