# Generated by Django 5.1.6 on 2025-03-16 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0002_alter_animal_options_alter_animal_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='for_breeding',
            field=models.BooleanField(default=False, verbose_name='for breeding'),
        ),
        migrations.AddField(
            model_name='breed',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animals', related_query_name='animal', to=settings.AUTH_USER_MODEL, verbose_name='sold to'),
        ),
    ]
