# Generated by Django 5.2 on 2025-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0003_alter_animal_managers_animal_for_breeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('short', 'short'), ('medium', 'medium'), ('long', 'long')], max_length=30, verbose_name='hair type'),
        ),
    ]
