# Generated by Django 5.2 on 2025-04-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0004_animal_hair_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='featured',
            field=models.BooleanField(default=True, help_text='Only featured breeds appear outside filters, such as on the homepage and navigation', verbose_name='featured'),
        ),
    ]
