# Generated by Django 5.2.7 on 2025-10-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0005_breed_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litter',
            old_name='expected_delivery_date',
            new_name='expected_ready_date',
        ),
        migrations.AddField(
            model_name='animal',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', related_query_name='animal', to='breeding.litter', verbose_name='litter'),
        ),
        migrations.AddField(
            model_name='litter',
            name='babies',
            field=models.PositiveIntegerField(blank=True, help_text='Actual number of babies born', null=True, verbose_name='babies'),
        ),
        migrations.AddField(
            model_name='litter',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Actual date when the litter was born', null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='litter',
            name='ready_date',
            field=models.DateField(blank=True, help_text='Actual date when babies were ready for new homes', null=True, verbose_name='ready date'),
        ),
        migrations.AddField(
            model_name='litter',
            name='status',
            field=models.CharField(choices=[('expecting', 'Expecting'), ('born', 'Born'), ('ready', 'Ready for new homes'), ('completed', 'All babies placed')], default='expecting', help_text='Current stage of the litter lifecycle', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('?', 'Unknown')], max_length=30, verbose_name='hair type'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='expected_babies',
            field=models.PositiveIntegerField(blank=True, help_text='Expected number of babies in this litter', null=True, verbose_name='expected babies'),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('kind', 'name'), ('kind', 'name_en'), ('kind', 'name_pt')},
        ),
    ]
