# Generated by Django 5.2.9 on 2025-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0006_litter_workflow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('kind', 'name'), ('kind', 'name_en'), ('kind', 'name_pt')},
        ),
        migrations.AddField(
            model_name='animal',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='animal',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='animal',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='animal',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='animalkind',
            name='name_de',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='animalkind',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='animalkind',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='animalkind',
            name='name_it',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='breed',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='breed',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='breed',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='breed',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='litter',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='litter',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='litter',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='litter',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='expected_ready_date',
            field=models.DateField(blank=True, help_text='Expected date when babies will be ready for new homes', null=True, verbose_name='expected ready date'),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('kind', 'name'), ('kind', 'name_de'), ('kind', 'name_en'), ('kind', 'name_es'), ('kind', 'name_fr'), ('kind', 'name_it'), ('kind', 'name_pt')},
        ),
    ]
