# Generated by Django 6.0 on 2026-01-06 16:03

from django.db import migrations
from django.conf import settings

DEFAULT_SITE_ID = 1
DEFAULT_SITE_DOMAIN = "example.com"
DEFAULT_SITE_NAME = "example.com"


def get_site_model(apps):
    return apps.get_model("sites", "Site")


def set_site_domain(apps, schema_editor):
    try:
        Site = get_site_model(apps)
    except LookupError:
        return  # sites framework not installed

    try:
        site = Site.objects.get(
            pk=getattr(settings, "SITE_ID", DEFAULT_SITE_ID)
        )

        site.domain = getattr(settings, "SITE_DOMAIN", DEFAULT_SITE_DOMAIN)
        site.name = getattr(settings, "SITE_NAME", DEFAULT_SITE_NAME)
        site.save()
    except Site.DoesNotExist:
        pass


def unset_site_domain(apps, schema_editor):
    try:
        Site = get_site_model(apps)
    except LookupError:
        return  # sites framework not installed

    try:
        site = Site.objects.get(
            pk=getattr(settings, "SITE_ID", DEFAULT_SITE_ID)
        )

        site.domain = DEFAULT_SITE_DOMAIN
        site.name = DEFAULT_SITE_NAME
        site.save()
    except Site.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('breeding', '0007_alter_breed_unique_together_animal_description_de_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=set_site_domain,
            reverse_code=unset_site_domain
        ),
    ]
