# Generated by Django 6.0.6 on 2026-07-22 23:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0009_chat_search_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='pre_reservation_enabled',
            field=models.BooleanField(default=True, verbose_name='available for pre-reservation'),
        ),
        migrations.AddField(
            model_name='animal',
            name='pre_reservation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Non-refundable pre-reservation fee in euros.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))], verbose_name='pre-reservation fee'),
        ),
        migrations.AddField(
            model_name='litter',
            name='pre_reservation_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Number of born babies offered for pre-reservation. Use zero to offer no places.', verbose_name='pre-reservation capacity'),
        ),
        migrations.AddField(
            model_name='litter',
            name='pre_reservation_enabled',
            field=models.BooleanField(default=True, verbose_name='available for pre-reservation'),
        ),
        migrations.AddField(
            model_name='litter',
            name='pre_reservation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Non-refundable pre-reservation fee in euros.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))], verbose_name='pre-reservation fee'),
        ),
        migrations.AddConstraint(
            model_name='litter',
            constraint=models.CheckConstraint(condition=models.Q(('pre_reservation_capacity', 0), models.Q(('babies__isnull', False), ('pre_reservation_capacity__lte', models.F('babies'))), _connector='OR'), name='litter_reservation_capacity_lte_babies'),
        ),
    ]
