# Generated by Django 6.0.6 on 2026-07-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0010_animal_pre_reservation_enabled_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='litter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'expecting'), _negated=True), ('pre_reservation_capacity', 0), _connector='OR'), name='expecting_litter_reservation_capacity_zero'),
        ),
    ]
