# Generated by Django 6.0.6 on 2026-07-23 15:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0014_remove_entity_chat_search_aliases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LitterAlertOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='subscribed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'litter alert override',
                'verbose_name_plural': 'litter alert overrides',
            },
        ),
        migrations.CreateModel(
            name='LitterAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('none', 'No general alerts'), ('all', 'All breeds'), ('selected_breeds', 'Selected breeds')], default='none', max_length=20, verbose_name='general litter alerts')),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'litter alert preference',
                'verbose_name_plural': 'litter alert preferences',
            },
        ),
        migrations.CreateModel(
            name='LitterBirthAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter_name', models.CharField(max_length=150)),
                ('breed_name', models.CharField(max_length=150)),
                ('babies', models.PositiveIntegerField()),
                ('birth_date', models.DateField()),
                ('announced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'litter birth announcement',
                'verbose_name_plural': 'litter birth announcements',
                'ordering': ['-announced_at'],
            },
        ),
        migrations.CreateModel(
            name='LitterBirthNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'litter birth notification',
                'verbose_name_plural': 'litter birth notifications',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='litter',
            name='litter_reservation_capacity_lte_babies',
        ),
        migrations.RemoveConstraint(
            model_name='litter',
            name='expecting_litter_reservation_capacity_zero',
        ),
        migrations.RenameField(
            model_name='litter',
            old_name='pre_reservation_enabled',
            new_name='offspring_pre_reservation_enabled',
        ),
        migrations.RenameField(
            model_name='litter',
            old_name='pre_reservation_fee',
            new_name='offspring_pre_reservation_fee',
        ),
        migrations.AddField(
            model_name='animal',
            name='reservation_deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Percentage of the dog price that must have been paid when the reservation is confirmed.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='reservation deposit percentage'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='offspring_pre_reservation_enabled',
            field=models.BooleanField(default=True, verbose_name='generated dogs available for pre-reservation'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='offspring_pre_reservation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Non-refundable pre-reservation fee copied to generated dogs.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))], verbose_name='generated dogs pre-reservation fee'),
        ),
        migrations.AddField(
            model_name='litter',
            name='offspring_reservation_deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Reservation deposit percentage copied to generated dogs.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='generated dogs reservation deposit percentage'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.CheckConstraint(condition=models.Q(('discount_in_euros__isnull', True), models.Q(('discount_in_euros__lte', models.F('price_in_euros')), ('price_in_euros__isnull', False)), _connector='OR'), name='animal_discount_lte_price'),
        ),
        migrations.AddField(
            model_name='litteralertoverride',
            name='litter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_overrides', to='breeding.litter', verbose_name='litter'),
        ),
        migrations.AddField(
            model_name='litteralertoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litter_alert_overrides', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='litteralertpreference',
            name='breeds',
            field=models.ManyToManyField(blank=True, related_name='alert_preferences', to='breeding.breed', verbose_name='breeds'),
        ),
        migrations.AddField(
            model_name='litteralertpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litter_alert_preference', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='litterbirthannouncement',
            name='litter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_announcement', to='breeding.litter', verbose_name='litter'),
        ),
        migrations.AddField(
            model_name='litterbirthnotification',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='breeding.litterbirthannouncement'),
        ),
        migrations.AddField(
            model_name='litterbirthnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litter_birth_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='litter',
            name='pre_reservation_capacity',
        ),
        migrations.AddConstraint(
            model_name='litteralertoverride',
            constraint=models.UniqueConstraint(fields=('user', 'litter'), name='one_litter_alert_override_per_user'),
        ),
        migrations.AddConstraint(
            model_name='litterbirthnotification',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='one_birth_notification_per_user'),
        ),
    ]
