# Generated by Django 6.0.6 on 2026-07-23 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0015_litteralertoverride_litteralertpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='reservation_offer_hours',
            field=models.PositiveSmallIntegerField(default=72, help_text='Hours available to pay the reservation deposit after the breeder accepts the pre-reservation. Minimum 1 hour, maximum 7 days.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='reservation offer validity in hours'),
        ),
    ]
