# Generated by Django 6.0.6 on 2026-07-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0017_remove_duplicated_sale_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='father',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'gender': 'M'},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children_father',
                related_query_name='child_father',
                to='breeding.animal',
                verbose_name='father',
            ),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mother',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'gender': 'F'},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children_mother',
                related_query_name='child_mother',
                to='breeding.animal',
                verbose_name='mother',
            ),
        ),
        migrations.AlterField(
            model_name='litter',
            name='father',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'gender': 'M'},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='litter_father',
                related_query_name='litter_father',
                to='breeding.animal',
                verbose_name='father',
            ),
        ),
        migrations.AlterField(
            model_name='litter',
            name='mother',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'gender': 'F'},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='litter_mother',
                related_query_name='litter_mother',
                to='breeding.animal',
                verbose_name='mother',
            ),
        ),
    ]
