# Generated by Django 6.0.6 on 2026-07-22 23:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeding', '0010_animal_pre_reservation_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codes are stored and matched without letter case.', max_length=50, unique=True, verbose_name='promotion code')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], max_length=20, verbose_name='discount type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='discount value')),
                ('scope', models.CharField(choices=[('any', 'Any pre-reservation'), ('dogs', 'All dogs'), ('litters', 'All litters'), ('breeds', 'Selected breeds'), ('specific_dogs', 'Selected dogs'), ('specific_litters', 'Selected litters')], default='any', max_length=30, verbose_name='applies to')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited redemptions.', null=True, verbose_name='maximum redemptions')),
                ('max_redemptions_per_user', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited redemptions per user.', null=True, verbose_name='maximum redemptions per user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeds', models.ManyToManyField(blank=True, related_name='pre_reservation_promotions', to='breeding.breed', verbose_name='breeds')),
                ('dogs', models.ManyToManyField(blank=True, related_name='pre_reservation_promotions', to='breeding.animal', verbose_name='dogs')),
                ('litters', models.ManyToManyField(blank=True, related_name='pre_reservation_promotions', to='breeding.litter', verbose_name='litters')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='promotion_value_gt_zero'), models.CheckConstraint(condition=models.Q(('discount_type', 'fixed'), models.Q(('discount_type', 'percentage'), ('value__lte', 100)), _connector='OR'), name='promotion_percentage_lte_100')],
            },
        ),
    ]
