# Generated by Django 6.0.6 on 2026-07-23 15:43

from django.db import migrations, models


def migrate_dog_only_scopes(apps, schema_editor):
    Promotion = apps.get_model('discounts', 'Promotion')
    Promotion.objects.filter(scope='dogs').update(scope='any')
    Promotion.objects.filter(
        scope__in=('litters', 'specific_litters'),
    ).update(scope='any', active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_dog_only_scopes,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='litters',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='scope',
            field=models.CharField(choices=[('any', 'Any dog (all breeds)'), ('breeds', 'Selected breeds'), ('specific_dogs', 'Selected dogs')], default='any', max_length=30, verbose_name='applies to'),
        ),
    ]
