# Generated by Django 6.0.6 on 2026-07-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_remove_promotion_litters_alter_promotion_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='purchase_stage',
            field=models.CharField(choices=[('pre_reservation', 'Pre-reservation'), ('reservation', 'Reservation'), ('both', 'Pre-reservation and reservation')], default='pre_reservation', help_text='Choose whether the code can discount the pre-reservation fee, the reservation deposit, or either purchase.', max_length=20, verbose_name='purchase stage'),
        ),
    ]
