# Generated by Django 5.2.5 on 2025-09-02 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeding', '0005_breed_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='answer')),
                ('text_en', models.CharField(max_length=255, null=True, verbose_name='answer')),
                ('text_pt', models.CharField(max_length=255, null=True, verbose_name='answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='question')),
                ('text_en', models.CharField(max_length=255, null=True, verbose_name='question')),
                ('text_pt', models.CharField(max_length=255, null=True, verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='weight')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer', verbose_name='answer')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breeding.breed', verbose_name='breed')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='breeds',
            field=models.ManyToManyField(through='quiz.AnswerWeight', to='breeding.breed', verbose_name='breeds'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='quiz.question', verbose_name='question'),
        ),
    ]
