# Generated by Django 5.2.5 on 2025-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0005_breed_featured'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=999, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=999, verbose_name='order'),
        ),
        migrations.AlterUniqueTogether(
            name='answerweight',
            unique_together={('answer', 'breed')},
        ),
    ]
