# Generated by Django 5.2.5 on 2025-09-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='answerweight',
            options={'verbose_name': 'Answer Weight', 'verbose_name_plural': 'Answer Weights'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
