# Generated by Django 5.2.9 on 2025-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_options_alter_answerweight_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_de',
            field=models.CharField(max_length=255, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_es',
            field=models.CharField(max_length=255, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_it',
            field=models.CharField(max_length=255, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_de',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_es',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_it',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
    ]
