# Generated by Django 6.0.6 on 2026-07-22 23:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeding', '0010_animal_pre_reservation_enabled_and_more'),
        ('discounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'Sale document'), ('credit_note', 'Credit note')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('integrated', 'Integrated'), ('retryable_failure', 'Retryable failure'), ('needs_attention', 'Needs attention')], db_index=True, default='pending', max_length=30)),
                ('external_reference', models.CharField(max_length=100, unique=True)),
                ('erp_document_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('erp_document_number', models.CharField(blank=True, max_length=100)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('integrated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('pdf_status', models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('available', 'Available'), ('failed', 'Failed')], default='not_requested', max_length=20)),
                ('pdf_data', models.BinaryField(blank=True, null=True)),
                ('pdf_filename', models.CharField(blank=True, max_length=255)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('pdf_attempt_count', models.PositiveIntegerField(default=0)),
                ('pdf_last_error', models.TextField(blank=True)),
                ('pdf_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ERP document',
                'verbose_name_plural': 'ERP documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmailAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_attempts', to='reservations.erpdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPIntegrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('automatic', 'Automatic'), ('success_page', 'Payment success page'), ('admin', 'Administrator')], max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('reconciled', 'Reconciled existing document'), ('failed', 'Failed')], max_length=20)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_attempts', to='reservations.erpdocument')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PreReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_type', models.CharField(choices=[('dog', 'Dog'), ('litter', 'Litter')], max_length=10, verbose_name='target type')),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('payment_failed', 'Payment failed'), ('expired', 'Expired'), ('cancelled_by_user', 'Cancelled by customer'), ('cancelled_by_admin', 'Cancelled by staff'), ('fulfilled', 'Fulfilled')], db_index=True, default='pending_payment', max_length=30, verbose_name='status')),
                ('target_name', models.CharField(max_length=150, verbose_name='target name')),
                ('target_breed', models.CharField(max_length=150, verbose_name='breed')),
                ('target_birth_date', models.DateField(blank=True, null=True)),
                ('target_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_tax_number', models.CharField(blank=True, max_length=30)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('billing_postcode', models.CharField(blank=True, max_length=20)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_country', models.CharField(default='PT', max_length=2)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('promotion_code', models.CharField(blank=True, max_length=50)),
                ('promotion_discount_type', models.CharField(blank=True, max_length=20)),
                ('promotion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(max_length=50)),
                ('non_refundable_accepted_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_reservations', to='breeding.animal', verbose_name='dog')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_pre_reservations', to=settings.AUTH_USER_MODEL)),
                ('litter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_reservations', to='breeding.litter', verbose_name='litter')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_reservations', to='discounts.promotion', verbose_name='promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_reservations', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'pre-reservation',
                'verbose_name_plural': 'pre-reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('complimentary', 'Complimentary')], default='stripe', max_length=20)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refund_pending', 'Refund pending'), ('refund_failed', 'Refund failed'), ('refunded', 'Refunded')], db_index=True, default='initializing', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_checkout_url', models.TextField(blank=True)),
                ('stripe_checkout_expires_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('refund_attempt_count', models.PositiveIntegerField(default=0)),
                ('refund_next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.prereservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='erpdocument',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_documents', to='reservations.prereservation'),
        ),
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_events', to='reservations.prereservation')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prereservation',
            index=models.Index(fields=['status', 'created_at'], name='reservation_status_d19992_idx'),
        ),
        migrations.AddIndex(
            model_name='prereservation',
            index=models.Index(fields=['animal', 'status'], name='reservation_animal__f84727_idx'),
        ),
        migrations.AddIndex(
            model_name='prereservation',
            index=models.Index(fields=['litter', 'status'], name='reservation_litter__d5e20b_idx'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('litter__isnull', True), ('target_type', 'dog')), models.Q(('animal__isnull', True), ('litter__isnull', False), ('target_type', 'litter')), models.Q(('animal__isnull', True), ('litter__isnull', True)), _connector='OR'), name='pre_reservation_target_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='pre_reservation_fee_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='pre_reservation_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('fee_amount'))), name='pre_reservation_discount_lte_fee'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='pre_reservation_total_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='reservation_payment_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='erpdocument',
            constraint=models.UniqueConstraint(fields=('reservation', 'kind'), name='one_erp_document_kind_per_reservation'),
        ),
    ]
