# Generated by Django 6.0.6 on 2026-07-22 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0010_animal_pre_reservation_enabled_and_more'),
        ('discounts', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_payment', 'confirmed', 'fulfilled')), ('target_type', 'dog')), fields=('animal',), name='one_active_pre_reservation_per_dog'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_payment', 'confirmed', 'fulfilled')), ('target_type', 'litter')), fields=('litter', 'user'), name='one_active_litter_place_per_user'),
        ),
    ]
