# Generated by Django 6.0.6 on 2026-07-22 23:34

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0011_litter_expecting_litter_reservation_capacity_zero'),
        ('discounts', '0001_initial'),
        ('reservations', '0002_prereservation_one_active_pre_reservation_per_dog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('fee_amount'), '-', models.F('discount_amount')))), name='pre_reservation_total_matches_snapshot'),
        ),
    ]
