# Generated by Django 6.0.6 on 2026-07-22 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0011_litter_expecting_litter_reservation_capacity_zero'),
        ('discounts', '0001_initial'),
        ('reservations', '0003_prereservation_pre_reservation_total_matches_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prereservation',
            name='pre_reservation_target_matches_type',
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('litter__isnull', True), ('target_type', 'dog')), models.Q(('animal__isnull', True), ('litter__isnull', False), ('target_type', 'litter')), models.Q(('animal__isnull', True), ('litter__isnull', True), ('target_deleted_at__isnull', False)), _connector='OR'), name='pre_reservation_target_matches_type'),
        ),
    ]
