# Generated by Django 6.0.6 on 2026-07-23 10:24

from django.db import migrations, models


def mark_existing_unresolved_documents_as_uncertain(apps, schema_editor):
    erp_document = apps.get_model('reservations', 'ERPDocument')
    erp_document.objects.filter(
        erp_document_id__isnull=True,
        status__in=('processing', 'retryable_failure', 'needs_attention'),
    ).update(creation_uncertain=True)


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_prereservation_pre_reservation_target_matches_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpdocument',
            name='creation_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='erpdocument',
            name='creation_uncertain',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(
            mark_existing_unresolved_documents_as_uncertain,
            migrations.RunPython.noop,
        ),
    ]
