# Generated by Django 6.0.6 on 2026-07-23 11:07

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


INITIAL_VERSION = 'pre-reservation-v1'
INITIAL_DESCRIPTIONS = {
    'description': (
        'The amount paid for the pre-reservation is non-refundable if the '
        'customer cancels the pre-reservation.\n\nIf the purchase is completed, '
        'the amount paid for the pre-reservation is deducted in full from the '
        'final price of the dog.'
    ),
    'description_en': (
        'The amount paid for the pre-reservation is non-refundable if the '
        'customer cancels the pre-reservation.\n\nIf the purchase is completed, '
        'the amount paid for the pre-reservation is deducted in full from the '
        'final price of the dog.'
    ),
    'description_pt': (
        'O valor pago pela pré-reserva não é reembolsável se o cliente cancelar '
        'a pré-reserva.\n\nSe a compra for concluída, o valor pago pela '
        'pré-reserva é deduzido na totalidade do preço final do cão.'
    ),
    'description_es': (
        'El importe pagado por la prerreserva no es reembolsable si el cliente '
        'cancela la prerreserva.\n\nSi se completa la compra, el importe pagado '
        'por la prerreserva se descuenta íntegramente del precio final del perro.'
    ),
    'description_fr': (
        "Le montant versé pour la pré-réservation n'est pas remboursable si le "
        "client annule la pré-réservation.\n\nSi l'achat est finalisé, le "
        'montant versé pour la pré-réservation est intégralement déduit du prix '
        'final du chien.'
    ),
    'description_de': (
        'Der für die Vorreservierung gezahlte Betrag wird nicht erstattet, wenn '
        'der Kunde die Vorreservierung storniert.\n\nWird der Kauf abgeschlossen, '
        'wird der für die Vorreservierung gezahlte Betrag vollständig vom '
        'endgültigen Kaufpreis des Hundes abgezogen.'
    ),
    'description_it': (
        "L'importo versato per la pre-prenotazione non è rimborsabile se il "
        "cliente annulla la pre-prenotazione.\n\nSe l'acquisto viene completato, "
        "l'importo versato per la pre-prenotazione viene detratto integralmente "
        'dal prezzo finale del cane.'
    ),
}


def associate_existing_reservations(apps, schema_editor):
    PreReservation = apps.get_model('reservations', 'PreReservation')
    PreReservationTerms = apps.get_model(
        'reservations',
        'PreReservationTerms',
    )
    now = timezone.now()
    historical_versions = set(
        PreReservation.objects.exclude(terms_version='')
        .values_list('terms_version', flat=True)
        .distinct()
    )
    historical_versions.discard(INITIAL_VERSION)

    current_terms = PreReservationTerms.objects.create(
        version=INITIAL_VERSION,
        published_at=now,
        **INITIAL_DESCRIPTIONS,
    )
    terms_by_version = {INITIAL_VERSION: current_terms}
    for version in sorted(historical_versions):
        terms_by_version[version] = PreReservationTerms.objects.create(
            version=version,
            published_at=now - timedelta(seconds=1),
            **INITIAL_DESCRIPTIONS,
        )

    for version, terms in terms_by_version.items():
        PreReservation.objects.filter(terms_version=version).update(terms=terms)
    PreReservation.objects.filter(terms__isnull=True).update(terms=current_terms)


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_erpdocument_creation_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreReservationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='version')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_pt', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('description_fr', models.TextField(null=True, verbose_name='description')),
                ('description_de', models.TextField(null=True, verbose_name='description')),
                ('description_it', models.TextField(null=True, verbose_name='description')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
            ],
            options={
                'verbose_name': 'pre-reservation terms',
                'verbose_name_plural': 'pre-reservation terms',
                'ordering': ('-published_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='prereservation',
            name='terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.prereservationterms', verbose_name='accepted terms'),
        ),
        migrations.RunPython(
            associate_existing_reservations,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='prereservation',
            name='terms_version',
        ),
        migrations.AlterField(
            model_name='prereservation',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.prereservationterms', verbose_name='accepted terms'),
        ),
    ]
