# Generated by Django 6.0.6 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_prereservationterms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
