# Generated by Django 6.0.6 on 2026-07-23 15:43

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


MONEY = Decimal('0.01')
DEFAULT_DEPOSIT_PERCENTAGE = Decimal('50.00')


def migrate_existing_workflow_data(apps, schema_editor):
    Animal = apps.get_model('breeding', 'Animal')
    ERPDocument = apps.get_model('reservations', 'ERPDocument')
    Payment = apps.get_model('reservations', 'Payment')
    PaymentRefund = apps.get_model('reservations', 'PaymentRefund')
    PreReservation = apps.get_model('reservations', 'PreReservation')
    ProcessedStripeEvent = apps.get_model(
        'reservations',
        'ProcessedStripeEvent',
    )

    animals = {
        animal.pk: animal
        for animal in Animal.objects.filter(
            pk__in=PreReservation.objects.filter(
                target_type='dog',
                animal_id__isnull=False,
            ).values('animal_id')
        )
    }
    for pre_reservation in PreReservation.objects.filter(target_type='dog'):
        animal = animals.get(pre_reservation.animal_id)
        published_price = (
            animal.price_in_euros
            if animal and animal.price_in_euros is not None
            else Decimal('0.00')
        )
        discount = (
            animal.discount_in_euros
            if animal and animal.discount_in_euros is not None
            else Decimal('0.00')
        )
        price = max(published_price - discount, Decimal('0.00')).quantize(MONEY)
        percentage = (
            animal.reservation_deposit_percentage
            if animal
            else DEFAULT_DEPOSIT_PERCENTAGE
        )
        deposit = (
            price * percentage / Decimal('100')
        ).quantize(MONEY)
        PreReservation.objects.filter(pk=pre_reservation.pk).update(
            animal_price_amount=price,
            reservation_deposit_percentage=percentage,
            reservation_deposit_amount=deposit,
        )

    PreReservation.objects.filter(
        status__in=('confirmed', 'fulfilled'),
    ).update(status='awaiting_review')

    refunds_by_payment = {}
    for payment in Payment.objects.all():
        refund_status = None
        if payment.status == 'refund_pending':
            refund_status = 'pending'
        elif payment.status == 'refund_failed':
            refund_status = 'failed'
        elif payment.status == 'refunded':
            refund_status = 'succeeded'

        if refund_status:
            refund = PaymentRefund.objects.create(
                payment_id=payment.pk,
                calculation_type='full_remaining',
                amount=payment.amount,
                provider_loss_acknowledged=True,
                reason='Migrated from the legacy refund workflow.',
                status=refund_status,
                stripe_refund_id=payment.stripe_refund_id,
                attempt_count=payment.refund_attempt_count,
                next_retry_at=(
                    payment.refund_next_retry_at
                    if refund_status in ('pending', 'failed')
                    else None
                ),
                last_error=(
                    payment.last_error if refund_status == 'failed' else ''
                ),
                succeeded_at=(
                    payment.refunded_at
                    if refund_status == 'succeeded'
                    else None
                ),
                failed_at=(
                    payment.updated_at
                    if refund_status == 'failed'
                    else None
                ),
            )
            refunds_by_payment[payment.pk] = refund

        if payment.status in ('refund_pending', 'refund_failed'):
            Payment.objects.filter(pk=payment.pk).update(status='paid')

    payments_by_pre_reservation = dict(
        Payment.objects.values_list('pre_reservation_id', 'pk')
    )
    for document in ERPDocument.objects.all():
        payment_id = payments_by_pre_reservation.get(document.reservation_id)
        if payment_id is None:
            continue
        updates = {'payment_id': payment_id}
        if document.kind == 'credit_note':
            refund = refunds_by_payment.get(payment_id)
            if refund is None:
                payment = Payment.objects.get(pk=payment_id)
                refund = PaymentRefund.objects.create(
                    payment_id=payment_id,
                    calculation_type='full_remaining',
                    amount=payment.amount,
                    provider_loss_acknowledged=True,
                    reason='Migrated from a legacy ERP credit note.',
                    status='succeeded',
                    succeeded_at=document.integrated_at or document.updated_at,
                )
                refunds_by_payment[payment_id] = refund
            updates['refund_id'] = refund.pk
        ERPDocument.objects.filter(pk=document.pk).update(**updates)

    for event in ProcessedStripeEvent.objects.exclude(reservation_id=None):
        ProcessedStripeEvent.objects.filter(pk=event.pk).update(
            payment_id=payments_by_pre_reservation.get(event.reservation_id),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0015_litteralertoverride_litteralertpreference_and_more'),
        ('discounts', '0002_remove_promotion_litters_alter_promotion_scope'),
        ('reservations', '0008_defer_disabled_erp_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('target_percentage', 'Target percentage'), ('full_remaining', 'Full remaining amount')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('target_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('provider_fee_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Stripe fee snapshot')),
                ('provider_net_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Stripe net amount snapshot')),
                ('provider_loss_acknowledged', models.BooleanField(default=False, verbose_name='processing cost loss acknowledged')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'payment refund',
                'verbose_name_plural': 'payment refunds',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('offered', 'Awaiting customer'), ('pending_payment', 'Awaiting payment'), ('payment_failed', 'Payment failed'), ('confirmed', 'Reserved'), ('expired', 'Expired'), ('cancelled_by_user', 'Cancelled by customer'), ('cancelled_by_admin', 'Cancelled by staff')], db_index=True, default='offered', max_length=30, verbose_name='status')),
                ('pre_reservation_credit_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='pre-reservation credit')),
                ('deposit_target_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='reservation deposit target')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='reservation payment amount')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('offer_expires_at', models.DateTimeField(db_index=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='version')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_pt', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('description_fr', models.TextField(null=True, verbose_name='description')),
                ('description_de', models.TextField(null=True, verbose_name='description')),
                ('description_it', models.TextField(null=True, verbose_name='description')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
            ],
            options={
                'verbose_name': 'reservation terms',
                'verbose_name_plural': 'reservation terms',
                'ordering': ('-published_at', '-pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='erpdocument',
            name='one_erp_document_kind_per_reservation',
        ),
        migrations.RemoveConstraint(
            model_name='prereservation',
            name='one_active_pre_reservation_per_dog',
        ),
        migrations.RemoveConstraint(
            model_name='prereservation',
            name='one_active_litter_place_per_user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='reservation',
            new_name='pre_reservation',
        ),
        migrations.AlterField(
            model_name='payment',
            name='pre_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='reservations.prereservation', verbose_name='pre-reservation'),
        ),
        migrations.AddField(
            model_name='erpdocument',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_documents', to='reservations.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='financials_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='financials_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='financials_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='animal_price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='dog price snapshot'),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='reservation_deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='reservation deposit target snapshot'),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='reservation_deposit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='reservation deposit percentage snapshot'),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pre_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processedstripeevent',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_events', to='reservations.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initializing', 'Initializing'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], db_index=True, default='initializing', max_length=30),
        ),
        migrations.AlterField(
            model_name='prereservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('awaiting_review', 'Awaiting review'), ('accepted', 'Accepted'), ('not_accepted', 'Not accepted'), ('payment_failed', 'Payment failed'), ('expired', 'Expired'), ('cancelled_by_user', 'Cancelled by customer'), ('cancelled_by_admin', 'Cancelled by staff'), ('reservation_offer_expired', 'Reservation offer expired'), ('converted_to_reservation', 'Converted to reservation')], db_index=True, default='pending_payment', max_length=30, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='reservations.payment'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payment_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erpdocument',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_document', to='reservations.paymentrefund'),
        ),
        migrations.RunPython(
            migrate_existing_workflow_data,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_attempt_count',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_next_retry_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refunded_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_refund_id',
        ),
        migrations.RemoveField(
            model_name='processedstripeevent',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='erpdocument',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='erpdocument',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_documents', to='reservations.payment'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.CheckConstraint(condition=models.Q(('target_type', 'litter'), models.Q(('animal_price_amount__gte', 0), ('animal_price_amount__isnull', False), ('reservation_deposit_amount__gte', 0), ('reservation_deposit_amount__isnull', False), ('reservation_deposit_percentage__gt', 0), ('reservation_deposit_percentage__isnull', False), ('reservation_deposit_percentage__lte', 100)), ('target_deleted_at__isnull', False), _connector='OR'), name='dog_pre_reservation_has_price_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_payment', 'awaiting_review', 'accepted')), ('target_type', 'dog')), fields=('animal',), name='one_active_pre_reservation_per_dog'),
        ),
        migrations.AddConstraint(
            model_name='erpdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'sale')), fields=('payment',), name='one_sale_erp_document_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='erpdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'sale'), ('refund__isnull', True)), models.Q(('kind', 'credit_note'), ('refund__isnull', False)), _connector='OR'), name='erp_document_refund_matches_kind'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pre_reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='reservations.prereservation', verbose_name='pre-reservation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='animal_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='reservations.reservation', verbose_name='reservation'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal_reservation__isnull', True), ('pre_reservation__isnull', False)), models.Q(('animal_reservation__isnull', False), ('pre_reservation__isnull', True)), _connector='OR'), name='payment_has_exactly_one_purchase'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.reservationterms', verbose_name='accepted terms'),
        ),
        migrations.RemoveField(
            model_name='prereservation',
            name='fulfilled_at',
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_refund_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('target_percentage__isnull', True), models.Q(('target_percentage__gt', 0), ('target_percentage__lte', 100)), _connector='OR'), name='payment_refund_percentage_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation_type', 'target_percentage'), ('target_percentage__isnull', False)), models.Q(models.Q(('calculation_type', 'target_percentage'), _negated=True), ('target_percentage__isnull', True)), _connector='OR'), name='payment_refund_percentage_matches_type'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'offer_expires_at'], name='reservation_status_0a6ef1_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('pre_reservation_credit_amount__gte', 0)), name='reservation_credit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_target_amount__gte', 0)), name='reservation_deposit_target_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('payment_amount__gte', 0)), name='animal_reservation_payment_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('pre_reservation_credit_amount__lte', models.F('deposit_target_amount'))), name='reservation_credit_lte_deposit_target'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('payment_amount', django.db.models.expressions.CombinedExpression(models.F('deposit_target_amount'), '-', models.F('pre_reservation_credit_amount')))), name='reservation_payment_matches_target_minus_credit'),
        ),
    ]
