# Generated by Django 6.0.6 on 2026-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_paymentrefund_reservation_reservationterms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('offered', 'Awaiting customer'), ('pending_payment', 'Awaiting payment'), ('payment_failed', 'Payment failed'), ('confirmed', 'Reserved'), ('expired', 'Expired'), ('cancelled_by_admin', 'Cancelled by staff')], db_index=True, default='offered', max_length=30, verbose_name='status'),
        ),
    ]
