# Generated by Django 6.0.6 on 2026-07-23 18:38

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_promotion_purchase_stage'),
        ('reservations', '0010_alter_reservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_payment_matches_target_minus_credit',
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='reservation discount'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='discounts.promotion', verbose_name='promotion'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promotion_discount_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promotion_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='reservation_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', django.db.models.expressions.CombinedExpression(models.F('deposit_target_amount'), '-', models.F('pre_reservation_credit_amount')))), name='reservation_discount_lte_amount_due'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('payment_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('deposit_target_amount'), '-', models.F('pre_reservation_credit_amount')), '-', models.F('discount_amount')))), name='reservation_payment_matches_amount_due'),
        ),
    ]
