# Generated by Django 6.0.6 on 2026-07-23 21:31

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_sale_cases_and_charges(apps, schema_editor):
    AnimalSaleCase = apps.get_model('reservations', 'AnimalSaleCase')
    Charge = apps.get_model('reservations', 'Charge')
    ERPDocument = apps.get_model('reservations', 'ERPDocument')
    Payment = apps.get_model('reservations', 'Payment')
    PreReservation = apps.get_model('reservations', 'PreReservation')
    Reservation = apps.get_model('reservations', 'Reservation')

    active_pre_statuses = {
        'pending_payment',
        'awaiting_review',
        'accepted',
    }
    active_reservation_statuses = {
        'offered',
        'pending_payment',
        'payment_failed',
        'confirmed',
    }
    settled_payment_statuses = {
        'paid',
        'partially_refunded',
        'refunded',
    }

    for pre_reservation in PreReservation.objects.order_by('pk'):
        reservation = Reservation.objects.filter(
            pre_reservation_id=pre_reservation.pk,
        ).first()
        if pre_reservation.animal_id:
            try:
                animal = pre_reservation.animal
            except Exception:
                animal = None
        else:
            animal = None

        if pre_reservation.target_type != 'dog':
            case_status = 'closed'
        elif animal is not None and animal.sold_at:
            case_status = 'sold'
        elif (
            reservation is not None
            and reservation.status in active_reservation_statuses
        ):
            case_status = 'reservation'
        elif pre_reservation.status in active_pre_statuses:
            case_status = 'pre_reservation'
        else:
            case_status = 'closed'

        sale_case = AnimalSaleCase.objects.create(
            user_id=pre_reservation.user_id,
            animal_id=pre_reservation.animal_id,
            origin='online',
            status=case_status,
            target_name=pre_reservation.target_name,
            target_breed=pre_reservation.target_breed,
            target_birth_date=pre_reservation.target_birth_date,
            target_deleted_at=(
                pre_reservation.target_deleted_at
                or (
                    pre_reservation.created_at
                    if pre_reservation.animal_id is None
                    else None
                )
            ),
            animal_price_amount=pre_reservation.animal_price_amount,
            reservation_deposit_percentage=(
                pre_reservation.reservation_deposit_percentage
            ),
            reservation_deposit_amount=(
                pre_reservation.reservation_deposit_amount
            ),
            customer_name=pre_reservation.customer_name,
            customer_email=pre_reservation.customer_email,
            customer_phone=pre_reservation.customer_phone,
            customer_tax_number=pre_reservation.customer_tax_number,
            billing_address=pre_reservation.billing_address,
            billing_postcode=pre_reservation.billing_postcode,
            billing_city=pre_reservation.billing_city,
            billing_country=pre_reservation.billing_country,
            language_code=pre_reservation.language_code,
            currency=pre_reservation.currency,
            closed_at=(
                pre_reservation.cancelled_at
                if case_status == 'closed'
                else None
            ),
        )

        pre_payment = Payment.objects.filter(
            pre_reservation_id=pre_reservation.pk,
        ).first()
        pre_charge = Charge.objects.create(
            sale_case_id=sale_case.pk,
            stage='pre_reservation',
            status=(
                'paid'
                if pre_payment
                and pre_payment.status in settled_payment_statuses
                else (
                    'void'
                    if case_status in {'closed', 'transferred'}
                    else 'open'
                )
            ),
            subtotal_amount=pre_reservation.fee_amount,
            promotion_id=pre_reservation.promotion_id,
            promotion_discount_amount=pre_reservation.discount_amount,
            promotion_code=pre_reservation.promotion_code,
            promotion_discount_type=(
                pre_reservation.promotion_discount_type
            ),
            promotion_value=pre_reservation.promotion_value,
            currency=pre_reservation.currency,
            due_at=pre_reservation.hold_expires_at,
            voided_at=(
                pre_reservation.cancelled_at
                if case_status == 'closed'
                else None
            ),
            void_reason=(
                pre_reservation.cancellation_reason
                if case_status == 'closed'
                else ''
            ),
        )
        PreReservation.objects.filter(pk=pre_reservation.pk).update(
            sale_case_id=sale_case.pk,
            charge_id=pre_charge.pk,
        )
        if pre_payment:
            Payment.objects.filter(pk=pre_payment.pk).update(
                charge_id=pre_charge.pk,
            )
            ERPDocument.objects.filter(payment_id=pre_payment.pk).update(
                charge_id=pre_charge.pk,
            )

        if reservation is None:
            continue

        reservation_payment = Payment.objects.filter(
            animal_reservation_id=reservation.pk,
        ).first()
        reservation_charge = Charge.objects.create(
            sale_case_id=sale_case.pk,
            stage='reservation',
            status=(
                'paid'
                if reservation_payment
                and reservation_payment.status in settled_payment_statuses
                else (
                    'void'
                    if reservation.status
                    not in active_reservation_statuses
                    else 'open'
                )
            ),
            subtotal_amount=(
                reservation.deposit_target_amount
                - reservation.pre_reservation_credit_amount
            ),
            promotion_id=reservation.promotion_id,
            promotion_discount_amount=reservation.discount_amount,
            promotion_code=reservation.promotion_code,
            promotion_discount_type=reservation.promotion_discount_type,
            promotion_value=reservation.promotion_value,
            currency=reservation.currency,
            due_at=reservation.offer_expires_at,
            voided_at=reservation.cancelled_at or reservation.expired_at,
            void_reason=reservation.cancellation_reason,
        )
        Reservation.objects.filter(pk=reservation.pk).update(
            sale_case_id=sale_case.pk,
            charge_id=reservation_charge.pk,
            terms_acceptance_source=(
                'customer_online'
                if reservation.terms_accepted_at
                else 'pending_customer'
            ),
        )
        if reservation_payment:
            Payment.objects.filter(pk=reservation_payment.pk).update(
                charge_id=reservation_charge.pk,
            )
            ERPDocument.objects.filter(
                payment_id=reservation_payment.pk,
            ).update(charge_id=reservation_charge.pk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0016_animal_reservation_offer_hours'),
        ('discounts', '0003_promotion_purchase_stage'),
        ('reservations', '0011_remove_reservation_reservation_payment_matches_target_minus_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='final sale price')),
                ('sold_at', models.DateField(verbose_name='sold at')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'animal sale',
                'verbose_name_plural': 'animal sales',
                'ordering': ['-sold_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalSaleCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origin', models.CharField(choices=[('online', 'Online'), ('admin', 'Created by staff'), ('transfer', 'Transferred')], db_index=True, default='online', max_length=20, verbose_name='origin')),
                ('status', models.CharField(choices=[('pre_reservation', 'Pre-reservation'), ('reservation', 'Reservation'), ('sold', 'Sold'), ('closed', 'Closed'), ('transferred', 'Transferred')], db_index=True, default='pre_reservation', max_length=20, verbose_name='status')),
                ('target_name', models.CharField(max_length=150, verbose_name='target name')),
                ('target_breed', models.CharField(max_length=150, verbose_name='breed')),
                ('target_birth_date', models.DateField(blank=True, null=True)),
                ('target_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('animal_price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='dog price snapshot')),
                ('reservation_deposit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='reservation deposit percentage snapshot')),
                ('reservation_deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='reservation deposit target snapshot')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_tax_number', models.CharField(blank=True, max_length=30)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('billing_postcode', models.CharField(blank=True, max_length=20)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_country', models.CharField(default='PT', max_length=2)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'animal sale process',
                'verbose_name_plural': 'animal sale processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalWorkflowTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_stage', models.CharField(choices=[('pre_reservation', 'Pre-reservation'), ('reservation', 'Reservation'), ('sale', 'Final sale')], max_length=20)),
                ('target_stage', models.CharField(choices=[('pre_reservation', 'Pre-reservation'), ('reservation', 'Reservation'), ('sale', 'Final sale')], max_length=20)),
                ('available_value_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('transferred_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('retained_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'animal workflow transfer',
                'verbose_name_plural': 'animal workflow transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stage', models.CharField(choices=[('pre_reservation', 'Pre-reservation'), ('reservation', 'Reservation'), ('sale', 'Final sale')], db_index=True, max_length=20, verbose_name='stage')),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='open', max_length=20, verbose_name='status')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='subtotal')),
                ('promotion_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='promotion discount')),
                ('promotion_code', models.CharField(blank=True, max_length=50)),
                ('promotion_discount_type', models.CharField(blank=True, max_length=20)),
                ('promotion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'charge',
                'verbose_name_plural': 'charges',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChargeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual_discount', 'Manual discount'), ('surcharge', 'Surcharge'), ('waiver', 'Waiver'), ('correction', 'Correction')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Use a negative value to reduce the amount due.', max_digits=9)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'charge adjustment',
                'verbose_name_plural': 'charge adjustments',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CreditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'credit allocation',
                'verbose_name_plural': 'credit allocations',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exhausted', 'Exhausted'), ('void', 'Void')], db_index=True, default='active', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'customer credit',
                'verbose_name_plural': 'customer credits',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stage', models.CharField(choices=[('pre_reservation', 'Pre-reservation'), ('reservation', 'Reservation'), ('sale', 'Final sale')], max_length=20)),
                ('kind', models.CharField(choices=[('cancelled', 'Cancelled'), ('rejected', 'Not accepted'), ('expired', 'Expired'), ('transferred', 'Transferred')], max_length=20)),
                ('paid_value_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='available paid value')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('retained_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'workflow closure',
                'verbose_name_plural': 'workflow closures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='erpdocument',
            name='one_sale_erp_document_per_payment',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_has_exactly_one_purchase',
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_credit_lte_deposit_target',
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_discount_lte_amount_due',
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_payment_matches_amount_due',
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sale_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='processing_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('manual', 'Recorded manually')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='terms_acceptance_source',
            field=models.CharField(choices=[('customer_online', 'Accepted online by customer'), ('staff_recorded', 'Acceptance recorded by staff'), ('pending_customer', 'Awaiting customer acceptance')], default='customer_online', max_length=30, verbose_name='terms acceptance source'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='customer credit'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='terms_acceptance_source',
            field=models.CharField(choices=[('customer_online', 'Accepted online by customer'), ('staff_recorded', 'Acceptance recorded by staff'), ('pending_customer', 'Awaiting customer acceptance')], default='pending_customer', max_length=30, verbose_name='terms acceptance source'),
        ),
        migrations.AlterField(
            model_name='erpdocument',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_documents', to='reservations.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('card_terminal', 'Card terminal'), ('other', 'Other'), ('complimentary', 'Complimentary')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='prereservation',
            name='non_refundable_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prereservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('awaiting_review', 'Awaiting review'), ('accepted', 'Accepted'), ('not_accepted', 'Not accepted'), ('payment_failed', 'Payment failed'), ('expired', 'Expired'), ('cancelled_by_user', 'Cancelled by customer'), ('cancelled_by_admin', 'Cancelled by staff'), ('reservation_offer_expired', 'Reservation offer expired'), ('converted_to_reservation', 'Converted to reservation'), ('transferred', 'Transferred')], db_index=True, default='pending_payment', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='prereservation',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.prereservationterms', verbose_name='accepted terms'),
        ),
        migrations.AlterField(
            model_name='prereservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_reservations', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pre_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='reservations.prereservation', verbose_name='pre-reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pre_reservation_credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='pre-reservation credit'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('offered', 'Awaiting customer'), ('pending_payment', 'Awaiting payment'), ('payment_failed', 'Payment failed'), ('confirmed', 'Reserved'), ('expired', 'Expired'), ('cancelled_by_admin', 'Cancelled by staff'), ('transferred', 'Transferred')], db_index=True, default='offered', max_length=30, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='animalsale',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_animal_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalsalecase',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_cases', to='breeding.animal', verbose_name='dog'),
        ),
        migrations.AddField(
            model_name='animalsalecase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_animal_sale_cases', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='animalsalecase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animal_sale_cases', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='animalsale',
            name='sale_case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='reservations.animalsalecase'),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='sale_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_reservation', to='reservations.animalsalecase', verbose_name='sale process'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='sale_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='reservations.animalsalecase', verbose_name='sale process'),
        ),
        migrations.AddField(
            model_name='animalworkflowtransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_animal_workflow_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalworkflowtransfer',
            name='source_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='reservations.animalsalecase'),
        ),
        migrations.AddField(
            model_name='animalworkflowtransfer',
            name='target_case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer', to='reservations.animalsalecase'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='reservations.animalworkflowtransfer'),
        ),
        migrations.AddField(
            model_name='charge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sale_charges', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='charge',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='discounts.promotion', verbose_name='promotion'),
        ),
        migrations.AddField(
            model_name='charge',
            name='sale_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='reservations.animalsalecase', verbose_name='sale process'),
        ),
        migrations.AddField(
            model_name='animalsale',
            name='charge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_stage', to='reservations.charge'),
        ),
        migrations.AddField(
            model_name='erpdocument',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_documents', to='reservations.charge'),
        ),
        migrations.AddField(
            model_name='payment',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.charge', verbose_name='charge'),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_reservation_stage', to='reservations.charge', verbose_name='charge'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_stage', to='reservations.charge', verbose_name='charge'),
        ),
        migrations.RunPython(
            backfill_sale_cases_and_charges,
            noop_reverse,
        ),
        migrations.AddConstraint(
            model_name='erpdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'sale'), ('payment__isnull', False)), fields=('payment',), name='one_sale_erp_document_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='erpdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('charge__isnull', False), ('kind', 'sale')), fields=('charge',), name='one_sale_erp_document_per_charge'),
        ),
        migrations.AddConstraint(
            model_name='erpdocument',
            constraint=models.CheckConstraint(condition=models.Q(('charge__isnull', False), ('payment__isnull', False), ('refund__isnull', False), _connector='OR'), name='erp_document_has_financial_source'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('charge__isnull', False), ('pre_reservation__isnull', False), ('animal_reservation__isnull', False), _connector='OR'), name='payment_has_charge_or_legacy_purchase'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('animal_reservation__isnull', False), ('pre_reservation__isnull', False), _negated=True), name='payment_has_at_most_one_legacy_purchase'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('customer_credit_amount__gte', 0)), name='reservation_customer_credit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('pre_reservation_credit_amount__lte', django.db.models.expressions.CombinedExpression(models.F('deposit_target_amount'), '-', models.F('customer_credit_amount')))), name='reservation_credit_lte_deposit_target'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('deposit_target_amount'), '-', models.F('pre_reservation_credit_amount')), '-', models.F('customer_credit_amount')))), name='reservation_discount_lte_amount_due'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('payment_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('deposit_target_amount'), '-', models.F('pre_reservation_credit_amount')), '-', models.F('customer_credit_amount')), '-', models.F('discount_amount')))), name='reservation_payment_matches_amount_due'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('pre_reservation__isnull', False), ('sale_case__isnull', False), _connector='OR'), name='reservation_has_pre_reservation_or_sale_case'),
        ),
        migrations.AddField(
            model_name='chargeadjustment',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='reservations.charge'),
        ),
        migrations.AddField(
            model_name='chargeadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charge_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='reservations.charge'),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_credit_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='source_sale_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credits', to='reservations.animalsalecase'),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='source_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='reservations.animalworkflowtransfer'),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_purchase_credits', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='reservations.customercredit'),
        ),
        migrations.AddField(
            model_name='workflowclosure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_closures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowclosure',
            name='sale_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='reservations.animalsalecase'),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='source_closure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='reservations.workflowclosure'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='closure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='reservations.workflowclosure'),
        ),
        migrations.AddIndex(
            model_name='animalsalecase',
            index=models.Index(fields=['status', 'created_at'], name='reservation_status_6e64e7_idx'),
        ),
        migrations.AddIndex(
            model_name='animalsalecase',
            index=models.Index(fields=['animal', 'status'], name='reservation_animal__6680b0_idx'),
        ),
        migrations.AddIndex(
            model_name='animalsalecase',
            index=models.Index(fields=['user', 'created_at'], name='reservation_user_id_8aea18_idx'),
        ),
        migrations.AddConstraint(
            model_name='animalsalecase',
            constraint=models.CheckConstraint(condition=models.Q(('animal__isnull', False), ('target_deleted_at__isnull', False), _connector='OR'), name='sale_case_has_animal_or_deleted_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='animalsalecase',
            constraint=models.UniqueConstraint(condition=models.Q(('animal__isnull', False), ('status__in', ('pre_reservation', 'reservation'))), fields=('animal',), name='one_active_sale_case_per_animal'),
        ),
        migrations.AddConstraint(
            model_name='animalworkflowtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('available_value_amount__gte', 0)), name='workflow_transfer_available_value_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='animalworkflowtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('transferred_amount__gte', 0)), name='workflow_transfer_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='animalworkflowtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='workflow_transfer_refund_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='animalworkflowtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('retained_amount__gte', 0)), name='workflow_transfer_retained_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='animalworkflowtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('available_value_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('transferred_amount'), '+', models.F('refund_amount')), '+', models.F('retained_amount')))), name='workflow_transfer_split_matches_available_value'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('sale_case', 'stage'), name='one_charge_per_sale_case_stage'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='charge_subtotal_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('promotion_discount_amount__gte', 0)), name='charge_promotion_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('promotion_discount_amount__lte', models.F('subtotal_amount'))), name='charge_promotion_discount_lte_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='animalsale',
            constraint=models.CheckConstraint(condition=models.Q(('final_price__gte', 0)), name='animal_sale_final_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='chargeadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='charge_adjustment_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='creditallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_allocation_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='workflowclosure',
            constraint=models.CheckConstraint(condition=models.Q(('paid_value_amount__gte', 0)), name='workflow_closure_paid_value_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='workflowclosure',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='workflow_closure_refund_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='workflowclosure',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gte', 0)), name='workflow_closure_credit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='workflowclosure',
            constraint=models.CheckConstraint(condition=models.Q(('retained_amount__gte', 0)), name='workflow_closure_retained_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='workflowclosure',
            constraint=models.CheckConstraint(condition=models.Q(('paid_value_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('refund_amount'), '+', models.F('credit_amount')), '+', models.F('retained_amount')))), name='workflow_closure_split_matches_paid_value'),
        ),
        migrations.AddConstraint(
            model_name='customercredit',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_credit_amount_gt_zero'),
        ),
    ]
