# Generated by Django 6.0.6 on 2026-07-23 23:08

from decimal import Decimal
from django.db import migrations, models


def backfill_fiscal_document_amounts(apps, schema_editor):
    ERPDocument = apps.get_model('reservations', 'ERPDocument')
    settled_statuses = ('paid', 'partially_refunded', 'refunded')
    for document in ERPDocument.objects.select_related(
        'payment',
        'refund',
        'charge',
    ):
        if document.refund_id:
            amount = document.refund.amount
            currency = document.refund.payment.currency
        elif document.payment_id:
            amount = document.payment.amount
            currency = document.payment.currency
        else:
            payments = document.charge.payments.filter(
                status__in=settled_statuses,
            )
            amount = sum(
                (payment.amount for payment in payments),
                Decimal('0.00'),
            )
            if amount <= 0:
                adjustments = document.charge.adjustments.all()
                amount = (
                    document.charge.subtotal_amount
                    - document.charge.promotion_discount_amount
                    + sum(
                        (adjustment.amount for adjustment in adjustments),
                        Decimal('0.00'),
                    )
                )
            currency = document.charge.currency
        ERPDocument.objects.filter(pk=document.pk).update(
            amount=max(amount, Decimal('0.00')),
            currency=currency,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_customercredit_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpdocument',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=9, verbose_name='fiscal document amount'),
        ),
        migrations.AddField(
            model_name='erpdocument',
            name='currency',
            field=models.CharField(default='EUR', editable=False, max_length=3),
        ),
        migrations.RunPython(
            backfill_fiscal_document_amounts,
            migrations.RunPython.noop,
        ),
    ]
