# Generated by Django 6.0.6 on 2026-07-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_erpdocument_amount_erpdocument_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
