# Generated by Django 6.0.6 on 2026-07-24 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0016_animal_reservation_offer_hours'),
        ('discounts', '0003_promotion_purchase_stage'),
        ('reservations', '0015_payment_checkout_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='animalsalecase',
            name='one_active_sale_case_per_animal',
        ),
        migrations.RemoveConstraint(
            model_name='erpdocument',
            name='one_sale_erp_document_per_payment',
        ),
        migrations.RemoveConstraint(
            model_name='erpdocument',
            name='one_sale_erp_document_per_charge',
        ),
        migrations.RemoveConstraint(
            model_name='prereservation',
            name='one_active_pre_reservation_per_dog',
        ),
        migrations.AddField(
            model_name='animalsalecase',
            name='active_animal_key',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(status__in=('pre_reservation', 'reservation'), then=models.F('animal')), default=models.Value(None)), null=True, output_field=models.BigIntegerField(null=True)),
        ),
        migrations.AddField(
            model_name='erpdocument',
            name='sale_charge_key',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(kind='sale', then=models.F('charge')), default=models.Value(None)), null=True, output_field=models.BigIntegerField(null=True)),
        ),
        migrations.AddField(
            model_name='erpdocument',
            name='sale_payment_key',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(kind='sale', then=models.F('payment')), default=models.Value(None)), null=True, output_field=models.BigIntegerField(null=True)),
        ),
        migrations.AddField(
            model_name='prereservation',
            name='active_animal_key',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(status__in=('pending_payment', 'awaiting_review', 'accepted'), target_type='dog', then=models.F('animal')), default=models.Value(None)), null=True, output_field=models.BigIntegerField(null=True)),
        ),
        migrations.AddConstraint(
            model_name='animalsalecase',
            constraint=models.UniqueConstraint(fields=('active_animal_key',), name='one_active_sale_case_per_animal'),
        ),
        migrations.AddConstraint(
            model_name='erpdocument',
            constraint=models.UniqueConstraint(fields=('sale_payment_key',), name='one_sale_erp_document_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='erpdocument',
            constraint=models.UniqueConstraint(fields=('sale_charge_key',), name='one_sale_erp_document_per_charge'),
        ),
        migrations.AddConstraint(
            model_name='prereservation',
            constraint=models.UniqueConstraint(fields=('active_animal_key',), name='one_active_pre_reservation_per_dog'),
        ),
    ]
