# Generated by Django 6.0.6 on 2026-07-24 11:26

import fortissimusbellator.contact_details
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_canonical_animal_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalsalecase',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, validators=[fortissimusbellator.contact_details.validate_international_phone]),
        ),
        migrations.AlterField(
            model_name='prereservation',
            name='customer_phone',
            field=models.CharField(max_length=30, validators=[fortissimusbellator.contact_details.validate_international_phone]),
        ),
    ]
