# Generated by Django 6.0.6 on 2026-07-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_animalsalecase_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentemailattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'document email attempt', 'verbose_name_plural': 'document email attempts'},
        ),
        migrations.AlterModelOptions(
            name='erpintegrationattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'ERP integration attempt', 'verbose_name_plural': 'ERP integration attempts'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='processedstripeevent',
            options={'ordering': ['-processed_at'], 'verbose_name': 'processed Stripe event', 'verbose_name_plural': 'processed Stripe events'},
        ),
    ]
