# Generated by Django 5.2 on 2025-04-05 18:29

import accounts.models
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('fiscal_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='fiscal number')),
                ('phone', models.CharField(max_length=15, verbose_name='phone number')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_picture_upload_to, verbose_name='profile picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', related_query_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_line1', models.CharField(max_length=255, verbose_name='Street Address 1')),
                ('street_line2', models.CharField(blank=True, max_length=255, verbose_name='Street Address 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state_province', models.CharField(max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('kind', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='billing', max_length=10, verbose_name='Address Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to='accounts.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
