# Generated by Django 6.0.6 on 2026-07-24 11:26

import fortissimusbellator.contact_details
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=16, validators=[fortissimusbellator.contact_details.validate_international_phone], verbose_name='phone number'),
        ),
    ]
