# Generated by Django 5.1.7 on 2025-03-28 11:22

import blog.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_pt', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('order', 'name', 'parent__name'),
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_pt', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('cover', models.ImageField(upload_to=blog.models.post_cover_upload_to, verbose_name='cover')),
                ('content', models.JSONField(verbose_name='content')),
                ('content_en', models.JSONField(null=True, verbose_name='content')),
                ('content_pt', models.JSONField(null=True, verbose_name='content')),
                ('published_at', models.DateTimeField(null=True, verbose_name='published at')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('categories', models.ManyToManyField(related_name='posts', related_query_name='post', to='blog.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('order', '-published_at'),
            },
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('commented_at', models.DateTimeField(verbose_name='commented_at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', related_query_name='reply', to='blog.comment', verbose_name='parent')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='blog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(verbose_name='liked at')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'blog')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='liked by')),
            ],
            options={
                'unique_together': {('liked_by', 'content_type', 'object_id')},
            },
        ),
    ]
