# Generated by Django 5.2.7 on 2025-10-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent'), ('name_en', 'parent'), ('name_pt', 'parent')},
        ),
    ]
