# Generated by Django 5.2.9 on 2025-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent'), ('name_en', 'parent'), ('name_pt', 'parent')},
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_de',
            field=models.JSONField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=models.JSONField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fr',
            field=models.JSONField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_it',
            field=models.JSONField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_it',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent'), ('name_de', 'parent'), ('name_en', 'parent'), ('name_es', 'parent'), ('name_fr', 'parent'), ('name_it', 'parent'), ('name_pt', 'parent')},
        ),
    ]
