# Generated by Django 5.1.7 on 2025-03-25 19:29

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True, verbose_name='tag')),
                ('tag_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='tag')),
                ('tag_pt', models.CharField(max_length=100, null=True, unique=True, verbose_name='tag')),
                ('color_light', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='light theme color')),
                ('color_dark', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='dark theme color')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'indexes': [models.Index(fields=['tag'], name='tags_tag_tag_2ec7df_idx'), models.Index(fields=['content_type', 'object_id'], name='tags_tag_content_9aa2bb_idx')],
                'unique_together': {('tag', 'content_type', 'object_id')},
            },
        ),
    ]
