# Generated by Django 5.2.7 on 2025-10-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'content_type', 'object_id'), ('tag_en', 'content_type', 'object_id'), ('tag_pt', 'content_type', 'object_id')},
        ),
    ]
