# Generated by Django 5.2.7 on 2025-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_en',
            field=models.CharField(max_length=100, null=True, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='tag'),
        ),
    ]
