# Generated by Django 5.2.9 on 2025-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0003_alter_tag_tag_alter_tag_tag_en_alter_tag_tag_pt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'content_type', 'object_id'), ('tag_en', 'content_type', 'object_id'), ('tag_pt', 'content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_de',
            field=models.CharField(max_length=100, null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_es',
            field=models.CharField(max_length=100, null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_it',
            field=models.CharField(max_length=100, null=True, verbose_name='tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'content_type', 'object_id'), ('tag_de', 'content_type', 'object_id'), ('tag_en', 'content_type', 'object_id'), ('tag_es', 'content_type', 'object_id'), ('tag_fr', 'content_type', 'object_id'), ('tag_it', 'content_type', 'object_id'), ('tag_pt', 'content_type', 'object_id')},
        ),
    ]
