"""Stable public facts shared by customer-facing application features."""

BUSINESS_NAME = "Fortissimus Bellator"
PRIMARY_PHONE = "+351 924 454 382"
SECONDARY_PHONE = "+351 916 749 407"
CONTACT_PHONES = f"{PRIMARY_PHONE} / {SECONDARY_PHONE}"
CONTACT_EMAIL = "geral@fortissimusbellator.pt"
ADDRESS = "Rua Quinta dos Frades, 904, 2400-821 Leiria, Portugal"
WEBSITE = "https://fortissimusbellator.pt"
WHATSAPP_URL = "https://wa.me/351924454382"
FACEBOOK_URL = "https://www.facebook.com/afixodefortissimusbellator"
INSTAGRAM_URL = "https://www.instagram.com/fortissimus_bellator/"
