"""
Django settings for fortissimusbellator project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import environ

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env(
    # <key>=(<casting>, <default-value>),
    SECRET_KEY=(
        str,
        'django-insecure-pu1c&f17&m0kg@%v6wdqnmam(v#dfb2+1qz-mlx519kgompj-x'
    ),

    DEBUG=(bool, False),

    EMAIL_HOST=(str, 'localhost'),
    EMAIL_PORT=(int, 25),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    EMAIL_USE_TLS=(bool, False),
    EMAIL_USE_SSL=(bool, False),

    DEFAULT_FROM_EMAIL=(str, 'no-reply@fortissimusbellator.pt'),

    RECIPIENT_LIST_ON_CONTACT_US_REQUEST=(
        list, ['geral@fortissimusbellator.pt', 'luiscosta2001@gmail.com']
    ),

    ALLOWED_HOSTS=(list, ['*']),

    DATABASE_URL=(str, 'sqlite:///db.sqlite3'),

    STATIC_ROOT=(str, BASE_DIR / 'static'),
    MEDIA_ROOT=(str, BASE_DIR / 'media'),

    RECAPTCHA_SITE_KEY=(str, ''),
    RECAPTCHA_SECRET_KEY=(str, ''),

    DEEPL_AUTH_KEY=(str, '')
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_USE_SSL = env('EMAIL_USE_SSL')

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
RECIPIENT_LIST_ON_CONTACT_US_REQUEST = env('RECIPIENT_LIST_ON_CONTACT_US_REQUEST')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

X_FRAME_OPTIONS = 'SAMEORIGIN'

XS_SHARING_ALLOWED_METHODS = ['HEAD', 'GET', 'OPTIONS',]

SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 3600  # 1 hour

# Application definition

INSTALLED_APPS = [
    # 3rd party apps that need to be before Django apps
    'modeltranslation',

    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party apps
    'django_recaptcha',
    'django_countries',
    'colorfield',

    'editorjs',
    'attachments',
    'tags',
    'accounts',
    'breeding',
    'frontoffice',
    'blog',
    'quiz',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fortissimusbellator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'fortissimusbellator' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'breeding.context_processors.featured_breeds',
                'frontoffice.context_processors.theme_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'fortissimusbellator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.db()
}


LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'welcome'  # Redirect after login
LOGOUT_REDIRECT_URL = 'home'    # Redirect after logout


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGES = [
    ("en", _("English")),
    ("pt", _("Portuguese")),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale'
]

LANGUAGE_CODE = 'pt'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

USE_TZ = True


FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = env('STATIC_ROOT')

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
    ('leaflet', BASE_DIR / 'node_modules/leaflet/dist'),
]

# Media files (Uploaded files)
# https://docs.djangoproject.com/en/5.0/ref/settings/#media-root
# https://docs.djangoproject.com/en/5.0/ref/settings/#media-url
MEDIA_ROOT = env('MEDIA_ROOT')

MEDIA_URL = 'media/'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Fixtures Directories to lookup
# https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-FIXTURE_DIRS
FIXTURE_DIRS = [
    BASE_DIR / 'fixtures'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_SITE_KEY')
RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_SECRET_KEY')


EDITORJS_DEFAULT_PLUGINS = [
    '@editorjs/paragraph',
    '@editorjs/header',
    '@editorjs/list',
    '@editorjs/checklist',
    '@editorjs/quote',
    '@editorjs/raw',
    '@editorjs/image',
    '@editorjs/embed',
    '@editorjs/delimiter',
    '@editorjs/warning',
    '@editorjs/marker',
    '@editorjs/table',
]


EDITORJS_DEFAULT_CONFIG = {
    "tools": {
        'Paragraph': {
            'class': 'Paragraph',
            'preserveBlank': True
        },
        'Header': {
            'class': 'Header',
            'inlineToolbar': True,
            'config': {
                'levels': [1, 2, 3, 4, 5, 6],
                'defaultLevel': 1,
            }
        },
        'Checklist': {
            'class': 'Checklist',
            'inlineToolbar': True
        },
        'EditorjsList': {
            'class': 'EditorjsList',
            'inlineToolbar': True,
            'config': {
                'defaultStyle': 'unordered',
                'maxLevel': 3
            },
        },
        'Quote': {
            'class': 'Quote',
            'inlineToolbar': True
        },
        'RawTool': {
            'class': 'RawTool',
            'inlineToolbar': True
        },
        'ImageTool': {
            'class': 'ImageTool',
            'inlineToolbar': True,
            'config': {
                'additionalRequestHeaders': {
                    "X-CSRFTOKEN": '',
                },
                'endpoints': {
                    'byFile': '/editorjs/image/upload/file/',
                    'byUrl': '/editorjs/image/upload/url/',
                }
            }
        },
        'Embed': {
            'class': 'Embed',
            'inlineToolbar': True,
            'config': {
                'services': {
                    'facebook': True,
                    'instagram': True,
                    'youtube': True,
                    'vimeo': True,
                    'imgur': True,
                    'pinterest': True
                }
            }
        },
        'Delimiter': {
            'class': 'Delimiter',
            'inlineToolbar': True
        },
        'Warning': {
            'class': 'Warning',
            'inlineToolbar': True
        },
        'Marker': {
            'class': 'Marker',
            'inlineToolbar': True
        },
        'Table': {
            'class': 'Table',
            'inlineToolbar': True
        },
    }
}


DEEPL_AUTH_KEY = env('DEEPL_AUTH_KEY')
