"""
Django settings for fortissimusbellator project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path

import environ
from django.utils.csp import CSP
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Read .env file if it exists (for local development)
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)

env = environ.Env(
    # <key>=(<casting>, <default-value>),
    SECRET_KEY=(
        str,
        'django-insecure-pu1c&f17&m0kg@%v6wdqnmam(v#dfb2+1qz-mlx519kgompj-x'
    ),

    DEBUG=(bool, False),

    SECURE_SSL_REDIRECT=(bool, False),
    SESSION_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_SECURE=(bool, False),
    TRUST_PROXY_HTTPS=(bool, False),

    EMAIL_HOST=(str, 'localhost'),
    EMAIL_PORT=(int, 25),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    EMAIL_USE_TLS=(bool, False),
    EMAIL_USE_SSL=(bool, False),

    DEFAULT_FROM_EMAIL=(str, 'no-reply@fortissimusbellator.pt'),
    PUBLIC_SITE_URL=(str, ''),

    RECIPIENT_LIST_ON_CONTACT_US_REQUEST=(
        list, ['geral@fortissimusbellator.pt', 'luiscosta2001@gmail.com']
    ),

    STRIPE_SECRET_KEY=(str, ''),
    STRIPE_WEBHOOK_SECRET=(str, ''),

    RESERVATION_CHECKOUT_MINUTES=(int, 10),
    RESERVATION_ERP_MAX_AUTOMATIC_ATTEMPTS=(int, 3),
    RESERVATION_REFUND_MAX_AUTOMATIC_ATTEMPTS=(int, 5),
    RESERVATION_PDF_MAX_BYTES=(int, 15 * 1024 * 1024),
    LITTER_ALERT_MAX_AUTOMATIC_ATTEMPTS=(int, 5),

    TOCONLINE_ENABLED=(bool, False),
    TOCONLINE_BASE_URL=(str, 'https://api10.toconline.pt'),
    TOCONLINE_OAUTH_BASE_URL=(str, 'https://app10.toconline.pt/oauth'),
    TOCONLINE_OAUTH_CLIENT_ID=(str, ''),
    TOCONLINE_OAUTH_CLIENT_SECRET=(str, ''),
    TOCONLINE_OAUTH_REDIRECT_URI=(str, 'https://oauth.pstmn.io/v1/callback'),
    TOCONLINE_ALLOWED_DOWNLOAD_HOSTS=(list, ['toconline.pt']),
    TOCONLINE_TIMEOUT=(int, 10),
    TOCONLINE_PAYMENT_MECHANISM=(str, ''),
    TOCONLINE_TAX_CODE=(str, ''),
    TOCONLINE_TAX_PERCENTAGE=(str, ''),

    ALLOWED_HOSTS=(list, ['*']),

    DATABASE_URL=(str, 'sqlite:///db.sqlite3'),

    STATIC_ROOT=(str, BASE_DIR / 'static'),
    MEDIA_ROOT=(str, BASE_DIR / 'media'),

    RECAPTCHA_SITE_KEY=(str, ''),
    RECAPTCHA_SECRET_KEY=(str, ''),

    FACEBOOK_GRAPH_VERSION=(str, 'v24.0'),
    FACEBOOK_PAGE_ID=(str, ''),
    FACEBOOK_ACCESS_TOKEN=(str, ''),
    INSTAGRAM_ACCOUNT_ID=(str, ''),

    DEEPL_AUTH_KEY=(str, ''),

    CHAT_MODEL_DIR=(str, str(BASE_DIR / '.models')),
    CHAT_MODEL_AUTO_DOWNLOAD=(bool, True),
    CHAT_MODEL_DOWNLOAD_TIMEOUT=(int, 60),
    CHAT_MODEL_MAX_DOWNLOAD_BYTES=(int, 1_350_000_000),
    CHAT_CONTEXT_SIZE=(int, 2048),
    CHAT_MAX_OUTPUT_TOKENS=(int, 192),
    CHAT_THREADS=(int, 2),

    UPLOAD_MAX_FILE_BYTES=(int, 100 * 1024 * 1024),
    UPLOAD_MAX_CHUNK_BYTES=(int, 5 * 1024 * 1024),
    UPLOAD_CHUNK_MAX_AGE_SECONDS=(int, 24 * 60 * 60),
    EDITOR_IMAGE_MAX_BYTES=(int, 10 * 1024 * 1024),
    EDITOR_IMAGE_MAX_PIXELS=(int, 25_000_000),
    EDITOR_REMOTE_READ_TIMEOUT=(int, 15),
    EDITOR_REMOTE_MAX_REDIRECTS=(int, 3),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
SECURE_SSL_REDIRECT = env('SECURE_SSL_REDIRECT')
SESSION_COOKIE_SECURE = env('SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = env('CSRF_COOKIE_SECURE')
if env('TRUST_PROXY_HTTPS'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_USE_SSL = env('EMAIL_USE_SSL')

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
_LEGACY_BUSINESS_RECIPIENTS = env('RECIPIENT_LIST_ON_CONTACT_US_REQUEST')
BUSINESS_NOTIFICATION_RECIPIENTS = env.list(
    'BUSINESS_NOTIFICATION_RECIPIENTS',
    default=_LEGACY_BUSINESS_RECIPIENTS,
)
# Kept temporarily for deployments that still import the old setting.
RECIPIENT_LIST_ON_CONTACT_US_REQUEST = BUSINESS_NOTIFICATION_RECIPIENTS

STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET')
RESERVATION_CHECKOUT_MINUTES = env('RESERVATION_CHECKOUT_MINUTES')
RESERVATION_ERP_MAX_AUTOMATIC_ATTEMPTS = env(
    'RESERVATION_ERP_MAX_AUTOMATIC_ATTEMPTS'
)
RESERVATION_REFUND_MAX_AUTOMATIC_ATTEMPTS = env(
    'RESERVATION_REFUND_MAX_AUTOMATIC_ATTEMPTS'
)
RESERVATION_PDF_MAX_BYTES = env('RESERVATION_PDF_MAX_BYTES')
LITTER_ALERT_MAX_AUTOMATIC_ATTEMPTS = env(
    'LITTER_ALERT_MAX_AUTOMATIC_ATTEMPTS'
)

TOCONLINE_ENABLED = env('TOCONLINE_ENABLED')
TOCONLINE_BASE_URL = env('TOCONLINE_BASE_URL')
TOCONLINE_OAUTH_BASE_URL = env('TOCONLINE_OAUTH_BASE_URL') or None
TOCONLINE_OAUTH_CLIENT_ID = env('TOCONLINE_OAUTH_CLIENT_ID')
TOCONLINE_OAUTH_CLIENT_SECRET = env('TOCONLINE_OAUTH_CLIENT_SECRET')
TOCONLINE_OAUTH_REDIRECT_URI = env('TOCONLINE_OAUTH_REDIRECT_URI')
TOCONLINE_ALLOWED_DOWNLOAD_HOSTS = env('TOCONLINE_ALLOWED_DOWNLOAD_HOSTS')
TOCONLINE_TIMEOUT = env('TOCONLINE_TIMEOUT')
TOCONLINE_PAYMENT_MECHANISM = env('TOCONLINE_PAYMENT_MECHANISM')
TOCONLINE_TAX_CODE = env('TOCONLINE_TAX_CODE')
TOCONLINE_TAX_PERCENTAGE = env('TOCONLINE_TAX_PERCENTAGE')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

X_FRAME_OPTIONS = 'SAMEORIGIN'

XS_SHARING_ALLOWED_METHODS = ['HEAD', 'GET', 'OPTIONS',]

SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 31536000  # 1 year

# Cross-origin services such as OpenStreetMap need to identify the requesting
# website. Only send the origin over HTTPS; never expose paths or query strings.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

SECURE_CSP = {
    'default-src': [
        CSP.SELF
    ],
    'script-src': [
        CSP.SELF,
        CSP.UNSAFE_INLINE,  # django admin uses inline scripts
        CSP.UNSAFE_EVAL,  # Needed in production (mod_pagespeed)
        # f"'nonce-{request.csp_nonce}'",  # For inline scripts with nonce
        'https://cdn.jsdelivr.net',
        '*.google.com',
        '*.gstatic.com',
    ],
    'style-src': [
        CSP.SELF,
        CSP.UNSAFE_INLINE,
        'https://fonts.googleapis.com',
    ],
    'font-src': [
        CSP.SELF,
        'https://fonts.gstatic.com',
    ],
    'img-src': [
        CSP.SELF,
        'data:',
        'https://www.facebook.com',
        'https://www.instagram.com',
        'https://cdn.jsdelivr.net',
        '*.openstreetmap.org',
    ],
    'connect-src': [
        CSP.SELF,
    ],
    'frame-src': [
        CSP.SELF,
        '*.google.com',
        'https://www.instagram.com'
    ],
    'frame-ancestors': [
        CSP.NONE,
    ],
    'media-src': [
        CSP.NONE,
    ],
    'object-src': [
        CSP.NONE,
    ]
}

# Application definition

INSTALLED_APPS = [
    # 3rd party apps that need to be before Django apps
    'modeltranslation',

    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',

    # 3rd party apps
    'django_recaptcha',
    'django_countries',
    'colorfield',
    'toconline',

    'editorjs',
    'attachments',
    'tags',
    'accounts',
    'breeding',
    'discounts',
    'reservations',
    'frontoffice',
    'blog',
    'quiz',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django_permissions_policy.PermissionsPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fortissimusbellator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'fortissimusbellator' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'breeding.context_processors.featured_breeds',
                'frontoffice.context_processors.theme_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'fortissimusbellator.wsgi.application'

SITE_ID = 1
SITE_DOMAIN = 'fortissimusbellator.pt'
SITE_NAME = 'Fortissimus Bellator'
PUBLIC_SITE_URL = (
    env('PUBLIC_SITE_URL') or f'https://{SITE_DOMAIN}'
).rstrip('/')

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.db()
}


LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'welcome'  # Redirect after login
LOGOUT_REDIRECT_URL = 'home'    # Redirect after logout


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGES = [
    ("en", _("English")),
    ("pt", _("Portuguese")),
    ("es", _("Spanish")),
    ("fr", _("French")),
    ("de", _("German")),
    ("it", _("Italian")),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale'
]

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

USE_TZ = True


FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = env('STATIC_ROOT')

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
    ('leaflet', BASE_DIR / 'node_modules/leaflet/dist'),
]

# Media files (Uploaded files)
# https://docs.djangoproject.com/en/5.0/ref/settings/#media-root
# https://docs.djangoproject.com/en/5.0/ref/settings/#media-url
MEDIA_ROOT = env('MEDIA_ROOT')

MEDIA_URL = 'media/'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Fixtures Directories to lookup
# https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-FIXTURE_DIRS
FIXTURE_DIRS = [
    BASE_DIR / 'fixtures'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_SITE_KEY', '')
RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_SECRET_KEY', '')

PERMISSIONS_POLICY = {
    "accelerometer": [],
    "ambient-light-sensor": [],
    "autoplay": [],
    "camera": [],
    "display-capture": [],
    "encrypted-media": [],
    "fullscreen": [
        'self',
    ],
    "geolocation": [],
    "gyroscope": [],
    "interest-cohort": [],
    "magnetometer": [],
    "microphone": [],
    "midi": [],
    "payment": [],
    "usb": [],
}

EDITORJS_DEFAULT_PLUGINS = [
    '@editorjs/paragraph',
    '@editorjs/header',
    '@editorjs/list',
    '@editorjs/checklist',
    '@editorjs/quote',
    '@editorjs/raw',
    '@editorjs/image',
    '@editorjs/embed',
    '@editorjs/delimiter',
    '@editorjs/warning',
    '@editorjs/marker',
    '@editorjs/table',
]


EDITORJS_DEFAULT_CONFIG = {
    "tools": {
        'Paragraph': {
            'class': 'Paragraph',
            'preserveBlank': True
        },
        'Header': {
            'class': 'Header',
            'inlineToolbar': True,
            'config': {
                'levels': [1, 2, 3, 4, 5, 6],
                'defaultLevel': 1,
            }
        },
        'Checklist': {
            'class': 'Checklist',
            'inlineToolbar': True
        },
        'EditorjsList': {
            'class': 'EditorjsList',
            'inlineToolbar': True,
            'config': {
                'defaultStyle': 'unordered',
                'maxLevel': 3
            },
        },
        'Quote': {
            'class': 'Quote',
            'inlineToolbar': True
        },
        'RawTool': {
            'class': 'RawTool',
            'inlineToolbar': True
        },
        'ImageTool': {
            'class': 'ImageTool',
            'inlineToolbar': True,
            'config': {
                'additionalRequestHeaders': {
                    "X-CSRFTOKEN": '',
                },
                'endpoints': {
                    'byFile': '/editorjs/image/upload/file/',
                    'byUrl': '/editorjs/image/upload/url/',
                }
            }
        },
        'Embed': {
            'class': 'Embed',
            'inlineToolbar': True,
            'config': {
                'services': {
                    'facebook': True,
                    'instagram': True,
                    'youtube': True,
                    'vimeo': True,
                    'imgur': True,
                    'pinterest': True
                }
            }
        },
        'Delimiter': {
            'class': 'Delimiter',
            'inlineToolbar': True
        },
        'Warning': {
            'class': 'Warning',
            'inlineToolbar': True
        },
        'Marker': {
            'class': 'Marker',
            'inlineToolbar': True
        },
        'Table': {
            'class': 'Table',
            'inlineToolbar': True
        },
    }
}

FACEBOOK_GRAPH_VERSION = env('FACEBOOK_GRAPH_VERSION')
FACEBOOK_PAGE_ID = env('FACEBOOK_PAGE_ID')
FACEBOOK_ACCESS_TOKEN = env('FACEBOOK_ACCESS_TOKEN')
INSTAGRAM_ACCOUNT_ID = env('INSTAGRAM_ACCOUNT_ID')

DEEPL_AUTH_KEY = env('DEEPL_AUTH_KEY')

# Local chat model. Defaults are deliberately conservative for a server with
# 2 GB RAM and 2 vCPUs. Run one web-server process so the model is loaded once.
CHAT_MODEL_DIR = env('CHAT_MODEL_DIR')
CHAT_MODEL_AUTO_DOWNLOAD = env('CHAT_MODEL_AUTO_DOWNLOAD')
CHAT_MODEL_DOWNLOAD_TIMEOUT = env('CHAT_MODEL_DOWNLOAD_TIMEOUT')
CHAT_MODEL_MAX_DOWNLOAD_BYTES = env('CHAT_MODEL_MAX_DOWNLOAD_BYTES')
CHAT_CONTEXT_SIZE = env('CHAT_CONTEXT_SIZE')
CHAT_MAX_OUTPUT_TOKENS = env('CHAT_MAX_OUTPUT_TOKENS')
CHAT_THREADS = env('CHAT_THREADS')
CHAT_BATCH_SIZE = 128
CHAT_MODEL_WAIT_SECONDS = 30
CHAT_MAX_INPUT_CHARS = 500
CHAT_MAX_RESPONSE_CHARS = 2000
CHAT_MAX_HISTORY_MESSAGES = 10
CHAT_KNOWLEDGE_MAX_CHARS = 4000
CHAT_MAX_FAQS = 3
CHAT_MAX_BLOG_POSTS = 10
CHAT_MAX_CERTIFICATIONS = 10
CHAT_MAX_KENNEL_ITEMS = 5
CHAT_REQUESTS_PER_MINUTE = 12

# Staff-only uploads are bounded to protect memory and disk on shared hosting.
UPLOAD_MAX_FILE_BYTES = env('UPLOAD_MAX_FILE_BYTES')
UPLOAD_MAX_CHUNK_BYTES = env('UPLOAD_MAX_CHUNK_BYTES')
UPLOAD_CHUNK_MAX_AGE_SECONDS = env('UPLOAD_CHUNK_MAX_AGE_SECONDS')
EDITOR_IMAGE_MAX_BYTES = env('EDITOR_IMAGE_MAX_BYTES')
EDITOR_IMAGE_MAX_PIXELS = env('EDITOR_IMAGE_MAX_PIXELS')
EDITOR_REMOTE_READ_TIMEOUT = env('EDITOR_REMOTE_READ_TIMEOUT')
EDITOR_REMOTE_MAX_REDIRECTS = env('EDITOR_REMOTE_MAX_REDIRECTS')

# Django's default logging hides application INFO messages.  Keep the model
# download/load lifecycle visible on hosts where there is no shell access.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'chat': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
