# Generated by Django 5.2.9 on 2025-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='description_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
    ]
